version: '3.9'

networks:
  app_network:
    driver: bridge
    external: false

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
      POSTGRES_DB: symptomatologic
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    restart: always
    command: >
        sh -c "python -m main.migrate migrate &&
              python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin_user:password@postgres:5432/symptomatologic
      SECRET_KEY: 9f37d951ec4d12453a2218334154f4d4c2ea57becc18907c9ac9e6e013f165c8
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    build: ./frontend
    restart: always
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL= http://127.0.0.1:8000
    depends_on:
      - backend
    networks:
      - app_network
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - app_network
